name: Deploy to cPanel

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy api
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy the application to the root directory on the cPanel server via FTP
      - name: Deploy to root directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./                             # Directory to upload
          server-dir: /                             # Remote root directory
          protocol: ftps                            # Use FTPS
          timeout: 600000                           # Set a high timeout for large projects
          log-level: verbose

      # Step 3: Deploy the application to the /horan-translator-bot/ directory on the cPanel server via FTP
      - name: Deploy to /horan-translator-bot/ directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./                             # Directory to upload
          server-dir: /horan-translator-bot/        # Remote directory for /horan-translator-bot/
          protocol: ftps                            # Use FTPS
          timeout: 600000                           # Set a high timeout for large projects
          log-level: verbose
